FROM node:20-alpine AS build
WORKDIR /app

COPY package.json ./

RUN apk add --no-cache python3 make gcc g++
RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine AS production
WORKDIR /app

COPY --from=build /app/.output /app/

ENV PORT=80
ENV HOST=0.0.0.0

# make sure to set the .env when using docker run or docker compose
ENV SPOTIFY_CLIENT_ID=
ENV SPOTIFY_CLIENT_SECRET=
ENV OSU_CLIENT_ID=
ENV OSU_CLIENT_SECRET=

EXPOSE 80

ENTRYPOINT [ "node", "/app/server/index.mjs" ]