version: "3.9"

services:
    wireguard:
        image: linuxserver/wireguard
        container_name: wireguard
        cap_add:
            - NET_ADMIN
        network_mode: "bridge"
        volumes:
            - /home/osu/vpn.conf:/config/wg0.conf
        sysctls:
            net.ipv4.conf.all.src_valid_mark: 1
            net.ipv4.ip_forward: 1
        restart: unless-stopped
    osus:
        image: rainwashed/osus:latest
        container_name: osus
        # ports:
        #     - "80:80"
        environment:
            - SPOTIFY_CLIENT_ID=47faeb86ac594731a890291a90dd4f4e
            - SPOTIFY_CLIENT_SECRET=bd2bcb07a1094439beaa264c4a609e40
            - SPOTIFY_PROXY_URL=http://spotify_tunnel:5000
            - OSU_CLIENT_ID=41656
            - OSU_CLIENT_SECRET=GMAbEdEMgJhPBteyTKSpOtDQfTE1pYjIvco156N7
            - OAUTH_REDIRECTION_LINK=https://osus.rainwashed.xyz/redirect
        depends_on:
            - wireguard
            - spotify_tunnel
        network_mode: "service:wireguard"
        restart: unless-stopped

    spotify_tunnel:
        image: rainwashed/spotify-public-proxy
        container_name: spotify_tunnel
        # ports:
        #     - "5000:5000"
        network_mode: "service:wireguard"
        restart: unless-stopped

    cloudflared:
        image: cloudflare/cloudflared
        container_name: cloudflared
        command: tunnel run --token eyJhIjoiOGFhYjViNDhhNjI5ZTg4NTg0ZjllNDg2MDQ0MzQ3YWIiLCJ0IjoiMDNhZGQ1ZjYtOWY2MS00MWIwLWI1OTYtNTcwOGZlYjkwYmEyIiwicyI6IlpUQXpPRFppT1RJdFpXVXdPQzAwTXpsa0xUZ3dObUV0WlRZeE5EVTFaRFZtWmprMCJ9 --protocol http2
        depends_on:
            osus:
                condition: service_started
        network_mode: "service:wireguard"
        restart: unless-stopped
